In [2]:
import numpy as np

In [3]:
actions = [
    (-1, -1),
    (-1, 0),
    (-1, 1),
    (0, -1),
    (0, 0),
    (0, 1),
    (1, -1),
    (1, 0),
    (1, 1),
]


In [5]:
for i, x in zip(range(9), actions):
    print(i, x)

0 (-1, -1)
1 (-1, 0)
2 (-1, 1)
3 (0, -1)
4 (0, 0)
5 (0, 1)
6 (1, -1)
7 (1, 0)
8 (1, 1)


In [6]:
np.add([2,3], [-1, 0])

array([1, 3])

In [13]:
def get_indices_of_valid_actions(velocity):
    indices_of_valid_acts = list()
    for idx, possible_action in enumerate(actions):
        new_velocity = np.add(velocity, possible_action)
        if (new_velocity[0] <= 5 and new_velocity[0] >=0) and (new_velocity[1] <=5 and new_velocity[1] >= 0):
            indices_of_valid_acts.append(idx)
    indices_of_valid_acts = np.array(indices_of_valid_acts)
    return indices_of_valid_acts

In [14]:
get_indices_of_valid_actions([5,5])

array([0, 1, 3, 4])

In [23]:
def map_to_one_dimension(action):
    for idx, possible_action in enumerate(actions):
        if list(action) == list(possible_action):
            return idx
        
map_to_one_dimension([0,1])

5

In [25]:
def map_to_2D(action):
    α = [(-1,-1),(-1,0),(0,-1),(-1,1),(0,0),(1,-1),(0,1),(1,0),(1,1)]
    return α[action]

In [26]:
map_to_2D(3)

(-1, 1)

In [30]:
ROWS = 200
COLS = 100

class Generator:
    
    #HELPFUL FUNCTIONS
    def widen_hole_transformation(self,racetrack,start_cell,end_cell):
        
        δ = 1
        while(1):
            if ((start_cell[1] < δ) or (start_cell[0] < δ)):
                racetrack[0:end_cell[0],0:end_cell[1]] = -1
                break

            if ((end_cell[1]+δ > COLS) or (end_cell[0]+δ > ROWS)):
                racetrack[start_cell[0]:ROWS,start_cell[1]:COLS] = -1
                break
                
            δ += 1

        return racetrack
    
    def calculate_valid_fraction(self, racetrack):
        '''
        Returns the fraction of valid cells in the racetrack
        '''
        return (len(racetrack[racetrack==0])/(ROWS*COLS))

    def mark_finish_states(self, racetrack):
        '''
        Marks finish states in the racetrack
        Returns racetrack
        '''
        last_col = racetrack[0:ROWS,COLS-1]
        last_col[last_col==0] = 2
        return racetrack
    
    def mark_start_states(self, racetrack):
        '''
        Marks start states in the racetrack
        Returns racetrack
        '''
        last_row = racetrack[ROWS-1,0:COLS]
        last_row[last_row==0] = 1
        return racetrack
    
    
    #CONSTRUCTOR
    def __init__(self):
        pass
    
    def generate_racetrack(self):
        '''
        racetrack is a 2d numpy array
        codes for racetrack:
            0,1,2 : valid racetrack cells
            -1: invalid racetrack cell
            1: start line cells
            2: finish line cells
        returns randomly generated racetrack
        '''
        racetrack = np.zeros((ROWS,COLS),dtype='int')
        
        frac = 1
        while frac > 0.5:    
            
            #transformation
            random_cell = np.random.randint((ROWS,COLS))
            random_hole_dims = np.random.randint((ROWS//4,COLS//4))
            start_cell = np.array([max(0,x - y//2) for x,y in zip(random_cell,random_hole_dims)])
            end_cell = np.array([min(z,x+y) for x,y,z in zip(start_cell,random_hole_dims,[ROWS,COLS])])
        
            #apply_transformation
            racetrack = self.widen_hole_transformation(racetrack, start_cell, end_cell)
            frac = self.calculate_valid_fraction(racetrack)
        
        racetrack = self.mark_start_states(racetrack)
        racetrack = self.mark_finish_states(racetrack)
        
        return racetrack

In [31]:
race_track = Generator().generate_racetrack()

In [33]:
race_track.shape

(200, 100)

In [36]:
temp = np.array([np.array([ROWS-1,j]) for j in range(COLS) if race_track[ROWS-1,j] == 1])
temp

array([[199,   0],
       [199,   1],
       [199,   2],
       [199,   3],
       [199,   4],
       [199,   5],
       [199,   6],
       [199,   7],
       [199,   8],
       [199,   9],
       [199,  10],
       [199,  11],
       [199,  12],
       [199,  13],
       [199,  14],
       [199,  15],
       [199,  16],
       [199,  17],
       [199,  18],
       [199,  19],
       [199,  20],
       [199,  21],
       [199,  22],
       [199,  23],
       [199,  24],
       [199,  25],
       [199,  26],
       [199,  27],
       [199,  28],
       [199,  29],
       [199,  30],
       [199,  31],
       [199,  32],
       [199,  33],
       [199,  34],
       [199,  35],
       [199,  36],
       [199,  37],
       [199,  38],
       [199,  39],
       [199,  40],
       [199,  41],
       [199,  42],
       [199,  43],
       [199,  44],
       [199,  45],
       [199,  46],
       [199,  47],
       [199,  48]])

In [37]:
temp.shape

(49, 2)

In [42]:
temp = np.load('/home/dhruvawasthi/Downloads/Q_vals.npy')

In [43]:
temp.shape

(200, 100, 5, 5, 9)

In [47]:
temp[0, 0, 0, 0]

array([-262.27231741, -443.18471719, -215.85641621, -356.47196215,
       -438.24962906, -306.83852415, -270.83723211, -179.4046092 ,
       -494.63356282])

In [ ]:
Q = rand(rows, cols, vel_len, vel_len, act_len) .* 400 .- 500
C = zeros(Float64, rows, cols, vel_len, vel_len, act_len)
π = ones(Int64, rows, cols, vel_len, vel_len)
for r = 1:rows, c = 1:cols, h = 1:vel_len, v = 1:vel_len
    π[r, c, h, v] = argmax(Q[r, c, h, v, :])
endt

In [52]:
(np.random.rand(5, 5, 6, 6, 9) * 400) - 500

array([[[[[-272.73657091, -171.17685372, -165.85893207, ...,
           -108.47099352, -218.28632344, -210.55257957],
          [-241.74124757, -137.90770901, -231.70082855, ...,
           -212.20779542, -423.2575131 , -200.23102077],
          [-260.77866228, -170.1600977 , -114.12912576, ...,
           -380.61565066, -120.76035626, -428.98050791],
          [-207.91261063, -408.19161639, -296.40095274, ...,
           -225.71742225, -273.68629131, -184.60083668],
          [-205.24062286, -100.1510833 , -451.58666803, ...,
           -484.13102722, -493.41016503, -136.7827654 ],
          [-398.8706504 , -338.91413564, -459.79738078, ...,
           -222.919804  , -187.38530122, -270.11014768]],

         [[-246.97602441, -111.1660448 , -166.70171001, ...,
           -165.77168303, -331.36564258, -416.05485593],
          [-189.4705395 , -274.06842286, -134.29391826, ...,
           -134.33121711, -129.70939835, -243.69751397],
          [-308.90712696, -284.84018461, -300.72448673

In [51]:
np.random.rand(5, 5, 6, 6, 9)

array([[[[[4.64113103e-01, 7.71481186e-01, 2.06329707e-01, ...,
           1.87978300e-01, 4.82441158e-01, 6.84644274e-01],
          [6.11211293e-01, 7.34004257e-01, 6.42927646e-02, ...,
           9.50692530e-01, 2.31955552e-01, 5.03802002e-01],
          [2.18295307e-01, 8.04137415e-02, 8.42533372e-02, ...,
           7.32805977e-01, 3.77831075e-01, 2.04228724e-01],
          [8.63274487e-01, 8.13372819e-01, 4.99973161e-01, ...,
           5.52810085e-01, 5.65221719e-01, 6.77327596e-01],
          [7.61818191e-01, 9.13507048e-01, 6.75890341e-01, ...,
           2.10095132e-01, 3.46863203e-01, 1.93976921e-01],
          [9.96576445e-01, 5.92604705e-01, 8.56073904e-01, ...,
           5.84945476e-01, 5.34690917e-01, 8.28245860e-01]],

         [[6.79064490e-01, 5.11599302e-01, 9.92949480e-02, ...,
           6.60021841e-01, 1.62172740e-02, 6.53615631e-01],
          [2.20087270e-01, 1.82890162e-01, 3.28872457e-01, ...,
           1.37962019e-01, 2.61245993e-01, 2.82024595e-01],
      

In [54]:
a = np.zeros((5, 5, 6, 6, 9),dtype="float64")

In [56]:
a

array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

        

In [60]:
policy = np.ones((26, 13, 6, 6), dtype="int64")
policy.shape

(26, 13, 6, 6)

In [61]:
Q_vals = (np.random.rand(26, 13, 6, 6, 9) * 400) - 500
Q_vals.shape

(26, 13, 6, 6, 9)

In [63]:
for i in range(26):
    for j in range(13):
        for h in range(6):
            for v in range(6):
                policy[i, j, h, v] = np.argmax(Q_vals[i, j, h, v, :])

In [64]:
policy

array([[[[0, 6, 5, 0, 2, 5],
         [3, 5, 6, 0, 5, 7],
         [1, 5, 3, 3, 5, 3],
         [3, 2, 6, 7, 6, 2],
         [8, 2, 6, 0, 7, 6],
         [8, 5, 2, 6, 6, 5]],

        [[4, 4, 2, 2, 2, 0],
         [2, 2, 2, 7, 7, 8],
         [0, 3, 4, 2, 3, 8],
         [5, 3, 5, 3, 5, 2],
         [4, 7, 1, 6, 8, 5],
         [2, 7, 7, 8, 4, 0]],

        [[4, 8, 7, 6, 4, 8],
         [6, 3, 3, 2, 2, 3],
         [3, 8, 5, 7, 3, 2],
         [6, 6, 3, 7, 1, 3],
         [2, 0, 5, 4, 2, 4],
         [8, 1, 1, 5, 4, 3]],

        ...,

        [[6, 6, 4, 6, 3, 1],
         [4, 4, 1, 5, 5, 6],
         [2, 8, 1, 8, 5, 4],
         [1, 6, 1, 5, 6, 8],
         [5, 4, 0, 0, 7, 8],
         [2, 5, 3, 1, 7, 4]],

        [[1, 0, 0, 7, 4, 0],
         [1, 6, 8, 6, 8, 7],
         [6, 6, 1, 5, 8, 0],
         [4, 2, 3, 0, 6, 1],
         [5, 8, 1, 0, 3, 7],
         [1, 5, 8, 5, 3, 2]],

        [[1, 6, 0, 0, 5, 6],
         [1, 8, 7, 8, 1, 6],
         [0, 6, 0, 2, 1, 0],
         [3, 0, 1, 

In [65]:
rewards = np.load("/home/dhruvawasthi/Downloads/rewards.npy")

In [66]:
rewards.shape

(0,)

In [67]:
rewards

array([], dtype=float64)

In [68]:
r = np.array([])

In [69]:
r

array([], dtype=float64)

In [70]:
r.shape

(0,)